name: Build and Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive_type: zip
            archive_platform_name: x86_64_windows
          - target: x86_64-unknown-linux-musl
            archive_type: tar.xz
            archive_platform_name: x86_64_linux
    steps:
      - uses: actions/checkout@v4
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          ARCHIVE_TYPES: ${{ matrix.archive_type }}
          ARCHIVE_NAME: json-lines-viewer-${{ matrix.archive_platform_name }}
          UPLOAD_MODE: release
#  publish-crate:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#    - name: Set up Rust
#      uses: actions-rs/toolchain@v1
#      with:
#        toolchain: nightly
#        profile: minimal
#        components: rustfmt
#    - name: Login to crates.io
#      run: cargo login ${{ secrets.CRATES_TOKEN }}
#    - name: Publish crate
#      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
