name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
          ARCHIVE_TYPES: "tar.gz tar.xz"
          ARCHIVE_NAME: "json-lines-viewer-${{ matrix.target }}.tar.gz"
          UPLOAD_MODE: release
